//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

interface LoginRequest
{
    username: string;
    password: string;
}
interface LoginResponse
{
    success: boolean;
    message: string;
    token: string;
}
interface PatientMeasurements
{
    data: MeasureDataDto[];
}
interface PatientWarnings
{
    data: PatientWarningDto[];
}
interface MeasureDataDto
{
    time: string;
    sys: number;
    dia: number;
    pulse: number;
}
interface MeasureDeviceDto
{
    id: number;
    manufacturer: string;
    model: string;
}
interface PatientDto
{
    id: number;
    firstName: string;
    lastName: string;
    gender: number;
    age: number;
    weight: number;
    devices: MeasureDeviceDto[];
}
interface PatientWarningDto
{
    id: number;
    patientId: number;
    measureDataId?: number;
    message: string;
    time: string;
}
interface UserDto
{
    id: number;
    userName: string;
    firstName: string;
    lastName: string;
    type: number;
    email: string;
    patients: PatientDto[];
}
