GET http://localhost:5003/user/me
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9zaWQiOiIxIiwiZXhwIjoxNzM3NDc4NjY1LCJpc3MiOiJBbGV4ZXlaYXZhciIsImF1ZCI6IlRlbm9tZXRlciJ9.mecjrB7x3kCos9LdPAWdzakhNjMtvOSKUX0UCMFgZeU
